#Config file for robot localization


frequency: 100

two_d_mode: true

publish_tf: false


odom_frame: odom
base_link_frame: base_link
world_frame: odom
# map_frame: map

odom0: /localization/wheel_encoder/raw
odom0_config: [false, false, false,
                false,  false,  false,
                true,  true,  false,
                false,  false,  true,
                false,  false,  false]
odom0_differential: false

# odom1: /odometry/filtered
# odom1_config: [true, true, false,
#                 false,  false,  false,
#                 false,  false,  false,
#                 false,  false,  false,
#                 false,  false,  false]
# odom1_differential: false

imu0: /localization/imu/raw
imu0_config: [false, false, false,
                false,  false,  true,
                false,  false,  false,
                false,  false,  false,
                true,  false,  false]
imu0_differential: false


publish_acceleration: true


